name: CI Test + Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v3

    - name: Build Docker image (force no cache)
      run: docker build --no-cache -t demo-devops .
