name: CI - Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Build Docker image (sans cache)
        run: docker build --no-cache -t demo-devops .
