name: CI Test + Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du dépôt
      uses: actions/checkout@v3

    - name: Test simple
      run: echo "CI exécuté avec succès !"

    - name: Build Docker image
      run: docker build -t demo-devops .